'use strict';

/**
 * WINDOWS — the launcher shims and the USER PATH.
 *
 * ------------------------------------------------------------------------
 * USER PATH, NOT MACHINE PATH. NEVER.
 *
 * Installing a CLI for yourself does not need administrator rights and must not
 * ask for them. `HKCU\Environment` is the user's own; `HKLM` is the machine's,
 * needs elevation, and a mistake there is a mistake for everybody who logs in.
 * Every read and write below is scoped `User`.
 *
 * ------------------------------------------------------------------------
 * WHY NOT `setx`, WHICH IS THE OBVIOUS ANSWER.
 *
 * `setx PATH "%PATH%;C:\new"` is the recipe everybody finds, and it is a trap
 * with two teeth:
 *
 *   1. IT TRUNCATES AT 1024 CHARACTERS, silently. A developer machine's PATH is
 *      routinely longer than that, so the "helpful" command quietly destroys the
 *      end of it — and the damage is only discovered later, by something that
 *      stopped being findable.
 *   2. `%PATH%` in a shell is the MERGED machine+user value, so writing it back
 *      to the user scope copies every machine entry into the user's own — which
 *      then never updates again when the machine's does.
 *
 * `[Environment]::GetEnvironmentVariable('PATH','User')` reads the user half
 * alone, and `SetEnvironmentVariable(...,'User')` writes it with no length
 * limit. That is the only correct pair, so it is the only one used.
 *
 * ------------------------------------------------------------------------
 * THREE SHIMS, BECAUSE WINDOWS HAS THREE SHELLS.
 *
 * `lain.cmd` for cmd.exe, `lain.ps1` for PowerShell, and an extensionless POSIX
 * `lain` for Git Bash / MSYS, which is how a great many people on Windows
 * actually work — including the machine this was built on. npm ships exactly
 * these three for the same reason.
 */

const { spawnSync } = require('child_process');
const path = require('path');

/** Run one PowerShell expression and return its trimmed stdout. */
function ps(expression, { timeout = 20000 } = {}) {
  const r = spawnSync('powershell.exe', [
    '-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-Command', expression,
  ], { encoding: 'utf8', windowsHide: true, timeout });
  if (r.error) throw r.error;
  if (r.status !== 0) throw new Error((r.stderr || '').trim() || `powershell exited ${r.status}`);
  return String(r.stdout || '').replace(/\r?\n$/, '');
}

/**
 * The PATH adapter pathenv.js drives. Read and write the USER scope only.
 *
 * A NULL USER PATH IS AN EMPTY STRING, NOT AN ERROR. A fresh Windows profile
 * genuinely has no user PATH, and PowerShell returns nothing for it — treating
 * that as a failure would refuse to install on exactly the machines that most
 * need the entry adding.
 */
const env = {
  sep: ';',
  get() {
    const v = ps("[Environment]::GetEnvironmentVariable('PATH','User')");
    return v === 'null' ? '' : v;
  },
  set(value) {
    // The value is passed through an argument rather than interpolated into the
    // script text, so a PATH containing quotes or `$` cannot become code.
    const encoded = Buffer.from(String(value), 'utf16le').toString('base64');
    ps(`$v=[Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('${encoded}'));`
      + "[Environment]::SetEnvironmentVariable('PATH',$v,'User')");
  },
  manual(dir) {
    return `[Environment]::SetEnvironmentVariable('PATH', `
      + `[Environment]::GetEnvironmentVariable('PATH','User') + ';${dir}', 'User')`;
  },
};

/** How Windows asks "where is this command?" */
function whichCommand(name) { return ['where.exe', [name]]; }

/**
 * THE SHIMS. `%~dp0` is the directory of the .cmd itself, so the launcher works
 * from any working directory and keeps working if the whole bin directory moves.
 *
 * `%*` UNQUOTED IS DELIBERATE and is the only form that passes arguments
 * through intact: `lain -p "fix the redirect"` must arrive as two arguments,
 * and any attempt to re-quote here mangles exactly the case that matters.
 */
function shims(target, nodeExe = 'node') {
  const node = nodeExe === 'node' ? 'node' : `"${nodeExe}"`;
  return {
    'lain.cmd': [
      '@echo off',
      'setlocal',
      `${node} "${target}" %*`,
      'endlocal',
      '',
    ].join('\r\n'),

    'lain.ps1': [
      '#!/usr/bin/env pwsh',
      '# LAIN Harness launcher. Generated by distribution/install.js — edits are lost on reinstall.',
      `& ${nodeExe === 'node' ? 'node' : `"${nodeExe}"`} "${target.replace(/\\/g, '\\\\')}" @args`,
      'exit $LASTEXITCODE',
      '',
    ].join('\r\n'),

    // Git Bash / MSYS. LF endings on purpose: a shell script with CRLF fails
    // with the famously unhelpful "bad interpreter: /usr/bin/env: no such file".
    lain: [
      '#!/bin/sh',
      '# LAIN Harness launcher. Generated by distribution/install.js — edits are lost on reinstall.',
      `exec node "${target.replace(/\\/g, '/')}" "$@"`,
      '',
    ].join('\n'),
  };
}

/** Which of the generated files must be executable. On Windows: none, meaningfully. */
const executable = ['lain'];

/**
 * Where a user-scope install belongs when the caller expresses no preference.
 * Under LAIN's own home, so an uninstall is one directory and nothing of the
 * user's is entangled with it.
 */
function defaultBin(home) { return path.join(home, 'bin'); }

module.exports = { env, shims, executable, defaultBin, whichCommand, ps };
