'use strict';

/**
 * THE MIGRATION TOOLS — three, and each one is a different question.
 *
 *   migration_plan      what is the final state supposed to be?
 *   migration_verify    is it that yet — INCLUDING the half nobody checks?
 *   migration_activate  retire the old implementation, reversibly
 *
 * ------------------------------------------------------------------------
 * WHY `migration_plan` ASKS THE USER ITSELF.
 *
 * The obvious design is for the model to call `ask_user` three times: which
 * agent, what happens to the old code, what happens to the JSON. That is three
 * round trips through the expensive model to deliver questions this program
 * generated locally and already knows the wording of — the model is being paid
 * to act as a courier.
 *
 * So when there is an interface to ask through, this asks. The questions are
 * DETERMINISTIC (migrationintent.js), the surface is the one MCQ panel every
 * other question uses (`ctx.ask`), and the answers come back inside the single
 * tool result as part of the contract. No screen is drawn here, no second
 * question system exists, and with no interactive UI it degrades to handing the
 * model the questions to ask in the ordinary way.
 *
 * IT DOES NOT SPEND THE CLARIFICATION BUDGET (clarify.js), and that is
 * deliberate. The budget exists to stop a model asking six times because it did
 * not want to look at the repository; these questions are the opposite — they
 * are the ones whose answers are NOT in the repository, generated by a local
 * analysis that has already looked. Charging them against the same allowance
 * would let a scope question starve a genuine one later in the task. They are
 * still RECORDED there, so nothing asks them twice.
 * ------------------------------------------------------------------------
 */

const M = require('../migration');
const intent = require('../migrationintent');
const map = require('../migrationmap');
const check = require('../migrationcheck');
const brief = require('../migrationbrief');
const structure = require('../structure');

/** Rounds of local questioning before this gives up and hands over the draft. */
const MAX_ROUNDS = 4;

function root(ctx) { return (ctx && ctx.cwd) || process.cwd(); }

/** The contract this call is about: the one named, or the one in flight. */
function pick(id) {
  const c = id ? M.load(String(id)) : M.latest();
  return c;
}

/** Questions rendered for a model to ask, when nothing can ask them here. */
function pendingBlock(questions) {
  const lines = ['AMBIGUOUS — these must be settled before any code is written.',
    'Ask them with ask_user (they are cheap; the migration they prevent is not),',
    'then call migration_plan again with `answers`.', ''];
  for (const q of questions) {
    lines.push(`  id: ${q.id}`);
    lines.push(`  ${q.question}`);
    for (const o of q.options) lines.push(`      - ${o}`);
    lines.push(`  why it matters: ${q.why}`);
    lines.push('');
  }
  return lines.join('\n');
}

/** Fold every answer we have — supplied or asked — into the draft. */
function applyAll(draft, questions, answers) {
  for (const q of questions) {
    const a = answers[q.id];
    if (a == null || a === '') continue;
    intent.applyAnswer(draft, q, a);
  }
  return draft;
}

const tools = {};

tools.migration_plan = {
  mutates: false,
  schema: {
    name: 'migration_plan',
    description:
      'Turn "migrate X to Y", "replace X with Y", "merge these three into one" or "change this button into a '
      + 'lever" into a MIGRATION CONTRACT before writing any code. "Migrate X to Y" does NOT mean "add Y" — it '
      + 'means the final state contains Y and NOT X, and this produces the document that says so: the exact '
      + 'scope, a file-by-file replacement map, the structure (responsibilities, not syntax) to carry across, '
      + 'which data and config to leave strictly alone, which code is OUTSIDE the scope and must survive '
      + 'untouched, who breaks when the old files go, and the checks that will be run afterwards — including '
      + 'the negative ones. It resolves ambiguity by asking the user directly where it can. '
      + 'Everything it reports is measured locally from the tree; call it FIRST, and work from what it returns '
      + 'rather than re-deriving the project.',
    parameters: {
      type: 'object',
      properties: {
        request: { type: 'string', description: "the user's own words for what should be migrated" },
        source: { type: 'string', description: 'the technology being migrated FROM, if the request did not say (e.g. "C++", "React", "webpack")' },
        target: { type: 'string', description: 'the technology being migrated TO, if the request did not say' },
        scope: {
          type: 'array',
          items: { type: 'string' },
          description: 'files or directories the migration is limited to. Give this whenever you know it: '
            + 'a scoped migration read as a project-wide one rewrites code nobody asked about.',
        },
        project_wide: { type: 'boolean', description: 'the user explicitly asked for the WHOLE project' },
        answers: {
          type: 'object',
          description: 'answers to questions a previous call returned, keyed by their id (e.g. {"scope": "Agent B", "old": "Replace it"})',
        },
      },
      required: ['request'],
    },
  },

  async run(input, ctx) {
    const request = String((input && input.request) || '').trim();
    if (!request) return { output: 'migration_plan needs the request it is planning for', isError: true };
    const cwd = root(ctx);

    const draft = intent.parse(request);
    if (input.source) draft.sourceName = String(input.source);
    if (input.target) draft.targetName = String(input.target);
    if (Array.isArray(input.scope) && input.scope.length) draft.paths = input.scope.map(String);
    if (input.project_wide) draft.projectWide = true;
    const answers = (input.answers && typeof input.answers === 'object') ? { ...input.answers } : {};

    let built = null;
    let asked = 0;
    for (let round = 0; round < MAX_ROUNDS; round++) {
      built = map.build(cwd, draft, { intent: request });
      const cls = built.classified;
      const dataResources = cls
        ? cls.preserve.filter((p) => structure.isData(p.path)).map((p) => p.path)
        : [];
      const questions = intent.questions(draft, {
        candidates: built.candidates,
        dataResources,
        sourcePresent: cls ? cls.translate.length : 0,
        // WHAT THE TREE ALREADY SETTLED. migrationmap resolves a scope the
        // request names in words — "change agent-b to Vue" names its own — and
        // without telling the question layer, the tool asked which agent
        // anyway and a mis-click migrated a different one.
        scopeResolved: built.resolved,
      });
      const pending = questions.filter((q) => !(draft.answers && draft.answers[q.id]) && answers[q.id] == null);
      if (!pending.length) { applyAll(draft, questions, answers); built = map.build(cwd, draft, { intent: request }); break; }

      // Answers supplied by the caller settle without asking anyone.
      const supplied = questions.filter((q) => answers[q.id] != null);
      if (supplied.length) { applyAll(draft, supplied, answers); continue; }

      if (typeof ctx.ask !== 'function') {
        const contract = built.contract;
        contract.open = pending.map((q) => ({ id: q.id, question: q.question, options: q.options, why: q.why }));
        try { M.save(contract); } catch { /* the manifest is a record, not the work */ }
        return {
          output: `${pendingBlock(pending)}\nDraft so far:\n${brief.oneLine(contract)}`,
          meta: { migration: contract.id, open: pending.length },
        };
      }

      const q = pending[0];
      const answer = await ctx.ask({ question: q.question, options: q.options, input: 'choice' });
      if (answer == null || answer === '') {
        return {
          output: 'The user dismissed the migration question without answering, so the scope and the fate of '
            + `the existing implementation are still unsettled:\n\n${pendingBlock(pending)}`,
          meta: { dismissed: true },
        };
      }
      answers[q.id] = answer;
      asked += 1;
      // RECORDED WHERE THE TASK KEEPS WHAT IT KNOWS, so it survives the turn,
      // compaction and /resume — and so nothing asks it again.
      try { require('../clarify').remember(ctx.app, q.question, answer); } catch { /* optional */ }
      applyAll(draft, [q], answers);
    }

    const contract = built.contract;
    contract.open = [];
    const valid = M.validate(contract);
    try { M.save(contract); } catch { /* a record, not the work */ }
    if (valid.ok) M.note(contract, M.STAGE.PLANNED, 'scope resolved, contract valid');

    const parts = [brief.render(contract)];
    if (!valid.ok) {
      parts.push('', 'THIS CONTRACT IS NOT YET VALID:');
      for (const p of valid.problems) parts.push(`  - ${p}`);
    }
    parts.push('', `Manifest: migration ${contract.id} (migration_verify checks it, migration_activate retires the source).`);
    if (asked) parts.push(`${asked} question(s) were settled with the user before this was written; do not ask them again.`);

    return {
      output: parts.join('\n'),
      isError: false,
      meta: {
        migration: contract.id,
        valid: valid.ok,
        operations: contract.operations.length,
        preserved: contract.resources.filter((r) => r.disposition === M.DISPOSITION.PRESERVE).length,
        asked,
      },
    };
  },
};

tools.migration_verify = {
  mutates: false,
  schema: {
    name: 'migration_verify',
    description:
      'Check a migration against BOTH halves of what was asked for: everything that must now exist and work, '
      + 'AND everything that must no longer be active — the old files gone, nothing still importing them, no '
      + 'surviving second implementation, and the code deliberately left OUTSIDE the scope untouched. A passing '
      + 'test suite proves only the first half, because a leftover implementation breaks nothing. Run this '
      + 'before reporting any migration, replacement or consolidation as done. Changes nothing.',
    parameters: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'the migration id; omit for the one in flight' },
      },
    },
  },

  async run(input, ctx) {
    const contract = pick(input && input.id);
    if (!contract) {
      return {
        output: 'No migration contract exists yet. Call migration_plan first — verifying a migration '
          + 'means checking it against what was agreed, and nothing has been agreed.',
        isError: true,
      };
    }
    const r = check.verify(root(ctx), contract);
    // THE STAGE IS MOVED BY EVIDENCE ONLY. Nothing here advances it because a
    // step was attempted; it advances because a check passed.
    if (r.ok) M.note(contract, (contract.archived || []).length ? M.STAGE.COMPLETE : M.STAGE.VERIFIED, 'all checks pass');
    else if (r.positiveOk) M.note(contract, M.STAGE.BUILT, 'target present; source still active');
    try { M.save(contract); } catch { /* a record, not the work */ }
    return {
      output: `${check.describe(r)}\n\n${brief.oneLine(contract)}`,
      isError: false,
      meta: { migration: contract.id, ok: r.ok, positiveOk: r.positiveOk, negativeOk: r.negativeOk, failures: r.failures.length },
    };
  },
};

tools.migration_activate = {
  mutates: true,
  schema: {
    name: 'migration_activate',
    description:
      'Retire the source implementation, reversibly, once the target is verified. Takes a project checkpoint, '
      + 'moves every file the contract marked ARCHIVE or REMOVE out of the tree into the migration archive, '
      + 're-verifies the FINAL state, and puts everything back automatically if that fails. Use this instead of '
      + 'deleting the old files yourself: a manual delete skips the checkpoint, the archive, the final-state '
      + 'check and the rollback. It refuses while any required check still fails.',
    parameters: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'the migration id; omit for the one in flight' },
        rollback: { type: 'boolean', description: 'undo an activation: restore the archived source implementation' },
        force: { type: 'boolean', description: 'archive even though required checks fail. Rarely right; say why in your answer.' },
      },
    },
  },

  async run(input, ctx) {
    const contract = pick(input && input.id);
    if (!contract) return { output: 'No migration contract exists. Call migration_plan first.', isError: true };
    const cwd = root(ctx);

    if (input.rollback) {
      const back = check.rollback(cwd, contract, { full: false });
      const left = back.targetsLeftInPlace;
      return {
        output: `Restored ${back.restored.length} archived file(s): ${back.restored.slice(0, 8).join(', ') || '(none were archived)'}\n`
          + `The source implementation is active again.${left.length ? `\nThe target files are still in the tree and were NOT removed: ${left.slice(0, 8).join(', ')}.` : ''}`,
        mutated: back.restored.map((r) => require('path').resolve(cwd, r)),
        meta: { migration: contract.id, restored: back.restored.length },
      };
    }

    const r = check.activate(cwd, contract, { force: Boolean(input.force) });
    if (!r.ok) {
      const parts = [r.why];
      if (r.verification) parts.push('', check.describe(r.verification));
      if (r.rolledBack) parts.push('', `Rolled back: ${r.rollback.restored.length} file(s) restored. The old implementation is active again.`);
      return { output: parts.join('\n'), isError: true, meta: { migration: contract.id, rolledBack: Boolean(r.rolledBack) } };
    }
    const lines = [
      `MIGRATION COMPLETE — ${brief.oneLine(contract)}`,
      '',
      `Checkpoint taken before anything moved: ${r.checkpoint ? r.checkpoint.id : '(none)'}`,
      `Archived out of the tree (${r.archived.length}): ${r.archived.map((a) => a.from).slice(0, 10).join(', ')}`,
      '',
      check.describe(r.verification),
    ];
    return {
      output: lines.join('\n'),
      mutated: r.archived.map((a) => require('path').resolve(cwd, a.from)),
      meta: { migration: contract.id, archived: r.archived.length, ok: true },
    };
  },
};

module.exports = { tools, pick, pendingBlock, MAX_ROUNDS };
